CREATE DATABASE MYSQL_DB_NAME;
CREATE USER 'SUPER_USER'@'%' IDENTIFIED BY 'SU_PWD';
--GRANT ALL PRIVILEGES ON *.* TO 'SUPER_USER'@'%' IDENTIFIED BY 'SU_PWD';
GRANT ALL PRIVILEGES ON MYSQL_DB_NAME.* TO 'SUPER_USER'@'%' IDENTIFIED BY 'SU_PWD';
FLUSH PRIVILEGES;
SHOW DATABASES;
select user,host from mysql.user;
SHOW GRANTS FOR 'SUPER_USER'@'%';
