CREATE DATABASE MYSQL_DB_NAME;
CREATE USER 'ARG_POWER_USER'@'%' IDENTIFIED BY 'ARG_PU_PWD';
--GRANT ALL PRIVILEGES ON *.* TO 'ARG_POWER_USER'@'%' IDENTIFIED BY 'ARG_PU_PWD';
GRANT ALL PRIVILEGES ON MYSQL_DB_NAME.* TO 'ARG_POWER_USER'@'%' IDENTIFIED BY 'ARG_PU_PWD';
FLUSH PRIVILEGES;
SHOW DATABASES;
select user,host from mysql.user;
SHOW GRANTS FOR 'ARG_POWER_USER'@'%';
