
#!/bin/bash
mysql -uroot -p${ROOT_PWD} <<EOF
CREATE DATABASE ${MYSQL_DB_NAME};
CREATE USER '${POWER_USER}'@'%' IDENTIFIED BY '${PU_PWD}';
-- GRANT ALL PRIVILEGES ON *.* TO '${POWER_USER}'@'%' IDENTIFIED BY '${PU_PWD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DB_NAME}.* TO '${POWER_USER}'@'%' IDENTIFIED BY '${PU_PWD}';
FLUSH PRIVILEGES;
SHOW DATABASES;
select user,host from mysql.user;
SHOW GRANTS FOR '${POWER_USER}'@'%';
EOF
